### ISSUE TITLE
telnet doesn't run and crashes editor

### ISSUE THREAD

**Issue by Xandaros** [OpenPrograms/Techokami-Programs#1]
Granted, this project is three years old and likely abandonware, but meh: Have an issue :P

The telnet program simply doesn't run - complaining about a syntax error on the first line.
The default editor crashes if you navigate to the last character on the first line (You can go past by pressing end, but going back one or deleting the last character is a problem), the editor crashes.

I believe this is caused by three control characters at the beginning of the file: 0xEFBBBF.
A quick google search told me, that these are a a magic number declaring the byte order. I don't know why these are necessary or why you decided to include them, but they seem to be causing issues.

**Comment by Techokami** [comment]
I blame OpenComputers evolving while I was taking a sabbatical from Minecraft. :V
So yeah, abandonware. You're free to fork and fix it!
